#!/usr/bin/python

'''
  This file is part of GNUKhata:A modular,robust and Free Accounting System.

  GNUKhata is Free Software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as
  published by the Free Software Foundation; either version 3 of
  the License, or (at your option) any later version.and old.stockflag = 's'

  GNUKhata is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public
  License along with GNUKhata (COPYING); if not, write to the
  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
  Boston, MA  02110-1301  USA59 Temple Place, Suite 330,


Contributor: "Krishnakant Mane" <krmane@gmail.com>
Krishnakant Mane <krmane@gmail.com>

'''


"""
import the main rpc module that starts gnukhata
the module is in gnukhataserver, the package for core engine.
We will also need the os module for executing other shell level commans.
This script will be plased in the user's /opt/gnukhata/bin directory.
It will have a symlink in /usr/bin so as to facilitate easy execution.
First the script will initialise the postgresql daemon from /opt/gnukhata/bin/postgres 
after the RDBMS the nginx web server will be started on port 80.
after that  the core engine will be started  followed by the web application.

"""
import gnukhataserver.rpc_main
import os
if __name__ == "__main__":
	try:
		os.system("sudo su -c '/usr/bin/postgres -D /var/data &' postgres")
		gnukhataserver.rpc_main.rungnukhata()
	except:
		print "can't start GNUKhata, some thing is wrong "

